const products = [
  // Chairs
  {
    id: 1,
    name: "Comfortable Chair",
    category: "Chair",
    price: 99,
    imageUrl: "/src/assets/product/chair-1.png",
    rating: 5,
  },
  {
    id: 2,
    name: "Ergonomic Chair",
    category: "Chair",
    price: 129,
    imageUrl: "/src/assets/product/chair-2.png",
    rating: 4,
  },
  {
    id: 3,
    name: "Stylish Armchair",
    category: "Chair",
    price: 149,
    imageUrl: "/src/assets/product/chair-3.png",
    rating: 3,
  },
  {
    id: 4,
    name: "Leather Recliner",
    category: "Chair",
    price: 199,
    imageUrl: "/src/assets/product/chair-4.png",
    rating: 4,
  },
  {
    id: 5,
    name: "Minimalist Chair",
    category: "Chair",
    price: 89,
    imageUrl: "/src/assets/product/chair-5.png",
    rating: 4.5,
  },

  // Beds
  {
    id: 6,
    name: "King Size Bed",
    category: "Beds",
    price: 299,
    imageUrl: "/src/assets/product/beds-1.png",
    rating: 5,
  },
  {
    id: 7,
    name: "Queen Size Bed",
    category: "Beds",
    price: 249,
    imageUrl: "/src/assets/product/beds-2.png",
    rating: 5,
  },
  {
    id: 8,
    name: "Modern Bed Frame",
    category: "Beds",
    price: 399,
    imageUrl: "/src/assets/product/beds-3.png",
    rating: 3,
  },
  {
    id: 9,
    name: "Platform Bed",
    category: "Beds",
    price: 349,
    imageUrl: "/src/assets/product/beds-4.png",
    rating: 2,
  },
  {
    id: 10,
    name: "Sleigh Bed",
    category: "Beds",
    price: 459,
    imageUrl: "/src/assets/product/beds-5.png",
    rating: 5,
  },

  // Sofas
  {
    id: 11,
    name: "Luxury Sofa",
    category: "Sofa",
    price: 499,
    imageUrl: "/src/assets/product/sofa-1.png",
    rating: 4,
  },
  {
    id: 12,
    name: "Compact Sofa",
    category: "Sofa",
    price: 399,
    imageUrl: "/src/assets/product/sofa-2.png",
    rating: 5,
  },
  {
    id: 13,
    name: "L-shaped Sofa",
    category: "Sofa",
    price: 699,
    imageUrl: "/src/assets/product/sofa-3.png",
    rating: 4,
  },
  {
    id: 14,
    name: "Sofa with Chaise",
    category: "Sofa",
    price: 549,
    imageUrl: "/src/assets/product/sofa-4.png",
    rating: 5,
  },
  {
    id: 15,
    name: "Sectional Sofa",
    category: "Sofa",
    price: 799,
    imageUrl: "/src/assets/product/sofa-5.png",
    rating: 3.6,
  },

  // Lamps
  {
    id: 16,
    name: "Modern Lamp",
    category: "Lamp",
    price: 49,
    imageUrl: "/src/assets/product/lamp-1.png",
    rating: 5,
  },
  {
    id: 17,
    name: "Classic Lamp",
    category: "Lamp",
    price: 59,
    imageUrl: "/src/assets/product/lamp-2.png",
    rating: 4,
  },
  {
    id: 18,
    name: "Wooden Table Lamp",
    category: "Lamp",
    price: 69,
    imageUrl: "/src/assets/product/lamp-3.png",
    rating: 3,
  },
  {
    id: 19,
    name: "Industrial Floor Lamp",
    category: "Lamp",
    price: 89,
    imageUrl: "/src/assets/product/lamp-4.png",
    rating: 5,
  },
  {
    id: 20,
    name: "Vintage Desk Lamp",
    category: "Lamp",
    price: 79,
    imageUrl: "/src/assets/product/lamp-6.png",
    rating: 4,
  },
];
export default products;
